name: Auto-Approve and Merge PR on Comment

on:
  issue_comment:
    types: [created]

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '✅')
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Approve and Merge PR
      if: contains(fromJson('["TickerDev", "thefourcraft"]'), github.event.comment.user.login)
      run: |
        gh pr review "${{ github.event.issue.pull_request.url }}" --approve
        gh pr merge "${{ github.event.issue.pull_request.url }}" --merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
